title: "Dokupeinu | HTB Writeups"
description: "Hack The Box writeups, penetration testing notes, and methodology."
url: "https://dokupeinu.github.io"
baseurl: "/HTB_Writeups"
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: false
permalink: /writeups/:title/
plugins:
  - jekyll-feed

collections:
  writeups:
    output: true
    permalink: /writeups/:name/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
